### ISSUE TITLE
Broken Image

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/ship#13]
Cheryl's image on the Ship team section is broken: it renders in Chrome but not Safari or Firefox, as the image file itself contains errors. I'm talking about the image at http://ship.techatnyu.org/lib/img/people/headshot/cheryl-wu.jpg. Presumably, it just got corrupted somehow and needs to be re-(saved, committed, and deployed) and then will work fine.

@grungerabbit

**Comment by AbhiAgarwal** [comment]
I think this fixed with the #18.
